### ISSUE TITLE
Lecture videos are truncated

### ISSUE THREAD

**Issue by rjcarr** [duliodenis/cs193p-Winter-2017#2]
Sorry, not sure where to get help.  I'm trying to get the lecture videos for this course but the downloads won't complete.  Yesterday, Lecture 1 was cutting off at 120MB exactly every time I tried.  And Lecture 2 was cutting off at exactly 26MB.  Strangely, today I'm getting to over 800MB before Lecture 1 fails, but it is still always at the same exact number.  Lecture 2 is still at 26MB.

I'm not on wifi and I tried a direct download (i.e., using curl and not just clicking in itunes).  And it still fails in the exact same spot.

It seems itunes is now the only source for these videos.  Any suggestions on what to do or who to contact?

**Comment by duliodenis** [comment]
The videos are huge - like well over 1GB each so you need a really good internet connection for iTunes.
Try watching them on YouTube: https://www.youtube.com/watch?v=zpVsrWvd47Y&list=PLVR6_Ck5fE5mrFejVploo5Xes9Vny8iRR
The first three are there and if past years are any indication the whole will be available with time.

**Comment by rjcarr** [comment]
Thanks for the youtube link.  My point about the download is that it is
failing at the same exact spot every time.  This tells me the video is
corrupted somehow.  I just tried it on a wired gigabit ethernet connection
and it failed at the same exact .  Anyway, I'll check out youtube, thanks
again!
